# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lance_service_pb2 as lance__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lance_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LanceSchedulerServiceStub(object):
    """Service running on the Scheduler for clients to submit Lance queries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnnSearch = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/AnnSearch',
                request_serializer=lance__service__pb2.AnnSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.FtsSearch = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/FtsSearch',
                request_serializer=lance__service__pb2.FtsSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/HybridSearch',
                request_serializer=lance__service__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetClusterStatus = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/GetClusterStatus',
                request_serializer=lance__service__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=lance__service__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)
        self.AddRows = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/AddRows',
                request_serializer=lance__service__pb2.AddRowsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.DeleteRows = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/DeleteRows',
                request_serializer=lance__service__pb2.DeleteRowsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.UpsertRows = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/UpsertRows',
                request_serializer=lance__service__pb2.UpsertRowsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.CreateTable = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/CreateTable',
                request_serializer=lance__service__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=lance__service__pb2.CreateTableResponse.FromString,
                _registered_method=True)
        self.ListTables = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/ListTables',
                request_serializer=lance__service__pb2.ListTablesRequest.SerializeToString,
                response_deserializer=lance__service__pb2.ListTablesResponse.FromString,
                _registered_method=True)
        self.DropTable = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/DropTable',
                request_serializer=lance__service__pb2.DropTableRequest.SerializeToString,
                response_deserializer=lance__service__pb2.DropTableResponse.FromString,
                _registered_method=True)
        self.CreateIndex = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/CreateIndex',
                request_serializer=lance__service__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=lance__service__pb2.CreateIndexResponse.FromString,
                _registered_method=True)
        self.AlterTable = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/AlterTable',
                request_serializer=lance__service__pb2.AlterTableRequest.SerializeToString,
                response_deserializer=lance__service__pb2.AlterTableResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/GetSchema',
                request_serializer=lance__service__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=lance__service__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.CountRows = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/CountRows',
                request_serializer=lance__service__pb2.CountRowsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.CountRowsResponse.FromString,
                _registered_method=True)
        self.Rebalance = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/Rebalance',
                request_serializer=lance__service__pb2.RebalanceRequest.SerializeToString,
                response_deserializer=lance__service__pb2.RebalanceResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/RegisterWorker',
                request_serializer=lance__service__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=lance__service__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.MoveShard = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/MoveShard',
                request_serializer=lance__service__pb2.MoveShardRequest.SerializeToString,
                response_deserializer=lance__service__pb2.MoveShardResponse.FromString,
                _registered_method=True)
        self.GetByIds = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/GetByIds',
                request_serializer=lance__service__pb2.GetByIdsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/Query',
                request_serializer=lance__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.BatchSearch = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/BatchSearch',
                request_serializer=lance__service__pb2.BatchSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.BatchSearchResponse.FromString,
                _registered_method=True)


class LanceSchedulerServiceServicer(object):
    """Service running on the Scheduler for clients to submit Lance queries.
    """

    def AnnSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FtsSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterStatus(self, request, context):
        """Cluster status (for monitoring/debugging)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRows(self, request, context):
        """Write operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """DDL operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterTable(self, request, context):
        """#5.3 Schema evolution: ADD COLUMN NULLABLE. Atomic across shards
        via the DDL lease (#5.2); bumps schema_version in MetaStore.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rebalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByIds(self, request, context):
        """Point lookup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Expression scan (SQL filter without vector)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSearch(self, request, context):
        """Batch vector search (multiple queries in one RPC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanceSchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnnSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnSearch,
                    request_deserializer=lance__service__pb2.AnnSearchRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'FtsSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FtsSearch,
                    request_deserializer=lance__service__pb2.FtsSearchRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=lance__service__pb2.HybridSearchRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'GetClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterStatus,
                    request_deserializer=lance__service__pb2.ClusterStatusRequest.FromString,
                    response_serializer=lance__service__pb2.ClusterStatusResponse.SerializeToString,
            ),
            'AddRows': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRows,
                    request_deserializer=lance__service__pb2.AddRowsRequest.FromString,
                    response_serializer=lance__service__pb2.WriteResponse.SerializeToString,
            ),
            'DeleteRows': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRows,
                    request_deserializer=lance__service__pb2.DeleteRowsRequest.FromString,
                    response_serializer=lance__service__pb2.WriteResponse.SerializeToString,
            ),
            'UpsertRows': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertRows,
                    request_deserializer=lance__service__pb2.UpsertRowsRequest.FromString,
                    response_serializer=lance__service__pb2.WriteResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=lance__service__pb2.CreateTableRequest.FromString,
                    response_serializer=lance__service__pb2.CreateTableResponse.SerializeToString,
            ),
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=lance__service__pb2.ListTablesRequest.FromString,
                    response_serializer=lance__service__pb2.ListTablesResponse.SerializeToString,
            ),
            'DropTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTable,
                    request_deserializer=lance__service__pb2.DropTableRequest.FromString,
                    response_serializer=lance__service__pb2.DropTableResponse.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=lance__service__pb2.CreateIndexRequest.FromString,
                    response_serializer=lance__service__pb2.CreateIndexResponse.SerializeToString,
            ),
            'AlterTable': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterTable,
                    request_deserializer=lance__service__pb2.AlterTableRequest.FromString,
                    response_serializer=lance__service__pb2.AlterTableResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=lance__service__pb2.GetSchemaRequest.FromString,
                    response_serializer=lance__service__pb2.GetSchemaResponse.SerializeToString,
            ),
            'CountRows': grpc.unary_unary_rpc_method_handler(
                    servicer.CountRows,
                    request_deserializer=lance__service__pb2.CountRowsRequest.FromString,
                    response_serializer=lance__service__pb2.CountRowsResponse.SerializeToString,
            ),
            'Rebalance': grpc.unary_unary_rpc_method_handler(
                    servicer.Rebalance,
                    request_deserializer=lance__service__pb2.RebalanceRequest.FromString,
                    response_serializer=lance__service__pb2.RebalanceResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=lance__service__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=lance__service__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'MoveShard': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveShard,
                    request_deserializer=lance__service__pb2.MoveShardRequest.FromString,
                    response_serializer=lance__service__pb2.MoveShardResponse.SerializeToString,
            ),
            'GetByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByIds,
                    request_deserializer=lance__service__pb2.GetByIdsRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=lance__service__pb2.QueryRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'BatchSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSearch,
                    request_deserializer=lance__service__pb2.BatchSearchRequest.FromString,
                    response_serializer=lance__service__pb2.BatchSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lance.distributed.LanceSchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lance.distributed.LanceSchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanceSchedulerService(object):
    """Service running on the Scheduler for clients to submit Lance queries.
    """

    @staticmethod
    def AnnSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/AnnSearch',
            lance__service__pb2.AnnSearchRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FtsSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/FtsSearch',
            lance__service__pb2.FtsSearchRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/HybridSearch',
            lance__service__pb2.HybridSearchRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/GetClusterStatus',
            lance__service__pb2.ClusterStatusRequest.SerializeToString,
            lance__service__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/AddRows',
            lance__service__pb2.AddRowsRequest.SerializeToString,
            lance__service__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/DeleteRows',
            lance__service__pb2.DeleteRowsRequest.SerializeToString,
            lance__service__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/UpsertRows',
            lance__service__pb2.UpsertRowsRequest.SerializeToString,
            lance__service__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/CreateTable',
            lance__service__pb2.CreateTableRequest.SerializeToString,
            lance__service__pb2.CreateTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/ListTables',
            lance__service__pb2.ListTablesRequest.SerializeToString,
            lance__service__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/DropTable',
            lance__service__pb2.DropTableRequest.SerializeToString,
            lance__service__pb2.DropTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/CreateIndex',
            lance__service__pb2.CreateIndexRequest.SerializeToString,
            lance__service__pb2.CreateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlterTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/AlterTable',
            lance__service__pb2.AlterTableRequest.SerializeToString,
            lance__service__pb2.AlterTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/GetSchema',
            lance__service__pb2.GetSchemaRequest.SerializeToString,
            lance__service__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/CountRows',
            lance__service__pb2.CountRowsRequest.SerializeToString,
            lance__service__pb2.CountRowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rebalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/Rebalance',
            lance__service__pb2.RebalanceRequest.SerializeToString,
            lance__service__pb2.RebalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/RegisterWorker',
            lance__service__pb2.RegisterWorkerRequest.SerializeToString,
            lance__service__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/MoveShard',
            lance__service__pb2.MoveShardRequest.SerializeToString,
            lance__service__pb2.MoveShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/GetByIds',
            lance__service__pb2.GetByIdsRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/Query',
            lance__service__pb2.QueryRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/BatchSearch',
            lance__service__pb2.BatchSearchRequest.SerializeToString,
            lance__service__pb2.BatchSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LanceExecutorServiceStub(object):
    """Service running on each Executor for receiving queries from Scheduler.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteLocalSearch = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/ExecuteLocalSearch',
                request_serializer=lance__service__pb2.LocalSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LocalSearchResponse.FromString,
                _registered_method=True)
        self.ExecuteLocalWrite = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/ExecuteLocalWrite',
                request_serializer=lance__service__pb2.LocalWriteRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LocalWriteResponse.FromString,
                _registered_method=True)
        self.LoadShard = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/LoadShard',
                request_serializer=lance__service__pb2.LoadShardRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LoadShardResponse.FromString,
                _registered_method=True)
        self.UnloadShard = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/UnloadShard',
                request_serializer=lance__service__pb2.UnloadShardRequest.SerializeToString,
                response_deserializer=lance__service__pb2.UnloadShardResponse.FromString,
                _registered_method=True)
        self.ExecuteCreateIndex = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/ExecuteCreateIndex',
                request_serializer=lance__service__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=lance__service__pb2.CreateIndexResponse.FromString,
                _registered_method=True)
        self.GetTableInfo = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/GetTableInfo',
                request_serializer=lance__service__pb2.GetTableInfoRequest.SerializeToString,
                response_deserializer=lance__service__pb2.GetTableInfoResponse.FromString,
                _registered_method=True)
        self.CompactAll = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/CompactAll',
                request_serializer=lance__service__pb2.CompactRequest.SerializeToString,
                response_deserializer=lance__service__pb2.CompactResponse.FromString,
                _registered_method=True)
        self.CreateLocalShard = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/CreateLocalShard',
                request_serializer=lance__service__pb2.CreateLocalShardRequest.SerializeToString,
                response_deserializer=lance__service__pb2.CreateLocalShardResponse.FromString,
                _registered_method=True)
        self.LocalGetByIds = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/LocalGetByIds',
                request_serializer=lance__service__pb2.GetByIdsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LocalSearchResponse.FromString,
                _registered_method=True)
        self.LocalQuery = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/LocalQuery',
                request_serializer=lance__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LocalSearchResponse.FromString,
                _registered_method=True)
        self.ExecuteAlterTable = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/ExecuteAlterTable',
                request_serializer=lance__service__pb2.LocalAlterTableRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LocalAlterTableResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/HealthCheck',
                request_serializer=lance__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=lance__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class LanceExecutorServiceServicer(object):
    """Service running on each Executor for receiving queries from Scheduler.
    """

    def ExecuteLocalSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteLocalWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCreateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTableInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompactAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLocalShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalGetByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAlterTable(self, request, context):
        """#5.3 Per-shard schema mutation — ADD COLUMN NULLABLE. Caller
        (coord) must hold the DDL lease (#5.2) before fanning this out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check (Scheduler periodically pings Executors)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanceExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteLocalSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteLocalSearch,
                    request_deserializer=lance__service__pb2.LocalSearchRequest.FromString,
                    response_serializer=lance__service__pb2.LocalSearchResponse.SerializeToString,
            ),
            'ExecuteLocalWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteLocalWrite,
                    request_deserializer=lance__service__pb2.LocalWriteRequest.FromString,
                    response_serializer=lance__service__pb2.LocalWriteResponse.SerializeToString,
            ),
            'LoadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadShard,
                    request_deserializer=lance__service__pb2.LoadShardRequest.FromString,
                    response_serializer=lance__service__pb2.LoadShardResponse.SerializeToString,
            ),
            'UnloadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadShard,
                    request_deserializer=lance__service__pb2.UnloadShardRequest.FromString,
                    response_serializer=lance__service__pb2.UnloadShardResponse.SerializeToString,
            ),
            'ExecuteCreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCreateIndex,
                    request_deserializer=lance__service__pb2.CreateIndexRequest.FromString,
                    response_serializer=lance__service__pb2.CreateIndexResponse.SerializeToString,
            ),
            'GetTableInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTableInfo,
                    request_deserializer=lance__service__pb2.GetTableInfoRequest.FromString,
                    response_serializer=lance__service__pb2.GetTableInfoResponse.SerializeToString,
            ),
            'CompactAll': grpc.unary_unary_rpc_method_handler(
                    servicer.CompactAll,
                    request_deserializer=lance__service__pb2.CompactRequest.FromString,
                    response_serializer=lance__service__pb2.CompactResponse.SerializeToString,
            ),
            'CreateLocalShard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLocalShard,
                    request_deserializer=lance__service__pb2.CreateLocalShardRequest.FromString,
                    response_serializer=lance__service__pb2.CreateLocalShardResponse.SerializeToString,
            ),
            'LocalGetByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalGetByIds,
                    request_deserializer=lance__service__pb2.GetByIdsRequest.FromString,
                    response_serializer=lance__service__pb2.LocalSearchResponse.SerializeToString,
            ),
            'LocalQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalQuery,
                    request_deserializer=lance__service__pb2.QueryRequest.FromString,
                    response_serializer=lance__service__pb2.LocalSearchResponse.SerializeToString,
            ),
            'ExecuteAlterTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAlterTable,
                    request_deserializer=lance__service__pb2.LocalAlterTableRequest.FromString,
                    response_serializer=lance__service__pb2.LocalAlterTableResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=lance__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=lance__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lance.distributed.LanceExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lance.distributed.LanceExecutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanceExecutorService(object):
    """Service running on each Executor for receiving queries from Scheduler.
    """

    @staticmethod
    def ExecuteLocalSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/ExecuteLocalSearch',
            lance__service__pb2.LocalSearchRequest.SerializeToString,
            lance__service__pb2.LocalSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteLocalWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/ExecuteLocalWrite',
            lance__service__pb2.LocalWriteRequest.SerializeToString,
            lance__service__pb2.LocalWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/LoadShard',
            lance__service__pb2.LoadShardRequest.SerializeToString,
            lance__service__pb2.LoadShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/UnloadShard',
            lance__service__pb2.UnloadShardRequest.SerializeToString,
            lance__service__pb2.UnloadShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/ExecuteCreateIndex',
            lance__service__pb2.CreateIndexRequest.SerializeToString,
            lance__service__pb2.CreateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTableInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/GetTableInfo',
            lance__service__pb2.GetTableInfoRequest.SerializeToString,
            lance__service__pb2.GetTableInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompactAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/CompactAll',
            lance__service__pb2.CompactRequest.SerializeToString,
            lance__service__pb2.CompactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLocalShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/CreateLocalShard',
            lance__service__pb2.CreateLocalShardRequest.SerializeToString,
            lance__service__pb2.CreateLocalShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocalGetByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/LocalGetByIds',
            lance__service__pb2.GetByIdsRequest.SerializeToString,
            lance__service__pb2.LocalSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocalQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/LocalQuery',
            lance__service__pb2.QueryRequest.SerializeToString,
            lance__service__pb2.LocalSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAlterTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/ExecuteAlterTable',
            lance__service__pb2.LocalAlterTableRequest.SerializeToString,
            lance__service__pb2.LocalAlterTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/HealthCheck',
            lance__service__pb2.HealthCheckRequest.SerializeToString,
            lance__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
