# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lance_service_pb2 as lance__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lance_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LanceSchedulerServiceStub(object):
    """Service running on the Scheduler for clients to submit Lance queries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnnSearch = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/AnnSearch',
                request_serializer=lance__service__pb2.AnnSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.FtsSearch = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/FtsSearch',
                request_serializer=lance__service__pb2.FtsSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/HybridSearch',
                request_serializer=lance__service__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetClusterStatus = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/GetClusterStatus',
                request_serializer=lance__service__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=lance__service__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)
        self.AddRows = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/AddRows',
                request_serializer=lance__service__pb2.AddRowsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.DeleteRows = channel.unary_unary(
                '/lance.distributed.LanceSchedulerService/DeleteRows',
                request_serializer=lance__service__pb2.DeleteRowsRequest.SerializeToString,
                response_deserializer=lance__service__pb2.WriteResponse.FromString,
                _registered_method=True)


class LanceSchedulerServiceServicer(object):
    """Service running on the Scheduler for clients to submit Lance queries.
    """

    def AnnSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FtsSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterStatus(self, request, context):
        """Cluster status (for monitoring/debugging)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRows(self, request, context):
        """Write operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanceSchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnnSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnSearch,
                    request_deserializer=lance__service__pb2.AnnSearchRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'FtsSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.FtsSearch,
                    request_deserializer=lance__service__pb2.FtsSearchRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=lance__service__pb2.HybridSearchRequest.FromString,
                    response_serializer=lance__service__pb2.SearchResponse.SerializeToString,
            ),
            'GetClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterStatus,
                    request_deserializer=lance__service__pb2.ClusterStatusRequest.FromString,
                    response_serializer=lance__service__pb2.ClusterStatusResponse.SerializeToString,
            ),
            'AddRows': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRows,
                    request_deserializer=lance__service__pb2.AddRowsRequest.FromString,
                    response_serializer=lance__service__pb2.WriteResponse.SerializeToString,
            ),
            'DeleteRows': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRows,
                    request_deserializer=lance__service__pb2.DeleteRowsRequest.FromString,
                    response_serializer=lance__service__pb2.WriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lance.distributed.LanceSchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lance.distributed.LanceSchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanceSchedulerService(object):
    """Service running on the Scheduler for clients to submit Lance queries.
    """

    @staticmethod
    def AnnSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/AnnSearch',
            lance__service__pb2.AnnSearchRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FtsSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/FtsSearch',
            lance__service__pb2.FtsSearchRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/HybridSearch',
            lance__service__pb2.HybridSearchRequest.SerializeToString,
            lance__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/GetClusterStatus',
            lance__service__pb2.ClusterStatusRequest.SerializeToString,
            lance__service__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/AddRows',
            lance__service__pb2.AddRowsRequest.SerializeToString,
            lance__service__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceSchedulerService/DeleteRows',
            lance__service__pb2.DeleteRowsRequest.SerializeToString,
            lance__service__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LanceExecutorServiceStub(object):
    """Service running on each Executor for receiving queries from Scheduler.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteLocalSearch = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/ExecuteLocalSearch',
                request_serializer=lance__service__pb2.LocalSearchRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LocalSearchResponse.FromString,
                _registered_method=True)
        self.ExecuteLocalWrite = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/ExecuteLocalWrite',
                request_serializer=lance__service__pb2.LocalWriteRequest.SerializeToString,
                response_deserializer=lance__service__pb2.LocalWriteResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/lance.distributed.LanceExecutorService/HealthCheck',
                request_serializer=lance__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=lance__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class LanceExecutorServiceServicer(object):
    """Service running on each Executor for receiving queries from Scheduler.
    """

    def ExecuteLocalSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteLocalWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check (Scheduler periodically pings Executors)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanceExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteLocalSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteLocalSearch,
                    request_deserializer=lance__service__pb2.LocalSearchRequest.FromString,
                    response_serializer=lance__service__pb2.LocalSearchResponse.SerializeToString,
            ),
            'ExecuteLocalWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteLocalWrite,
                    request_deserializer=lance__service__pb2.LocalWriteRequest.FromString,
                    response_serializer=lance__service__pb2.LocalWriteResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=lance__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=lance__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lance.distributed.LanceExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lance.distributed.LanceExecutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanceExecutorService(object):
    """Service running on each Executor for receiving queries from Scheduler.
    """

    @staticmethod
    def ExecuteLocalSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/ExecuteLocalSearch',
            lance__service__pb2.LocalSearchRequest.SerializeToString,
            lance__service__pb2.LocalSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteLocalWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/ExecuteLocalWrite',
            lance__service__pb2.LocalWriteRequest.SerializeToString,
            lance__service__pb2.LocalWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lance.distributed.LanceExecutorService/HealthCheck',
            lance__service__pb2.HealthCheckRequest.SerializeToString,
            lance__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
