apiVersion: v1
kind: Service
metadata:
  name: {{ include "lanceforge.fullname" . }}-worker-headless
  labels:
    {{- include "lanceforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: {{ .Values.worker.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "lanceforge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
